image:
  file: .gitpod.Dockerfile

tasks:
  - init: npm install
  - init: touch .env
    command: |
      echo "SESSION_SECRET=" >> .env"
      cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1 >> .env
      echo "\nLOCALDB_URL=mysql://root:\ @localhost:3306/test_db"
  - init: mysql -u root < db/schema.sql
    command: echo "Database Schema Initialized"